### PR TITLE
Distribute Capytaine with PyInstaller

### PR DESCRIPTION
**Pull request by mancellin**
Trying to build an independent executable from the conda-forge package.

TODO:
- [X] Have an executable working
- [x] Distribute the Nemoh-like command-line interface
- [ ] Distribute an executable able to run a Python script invoking Capytaine...
- [ ] ... including plots and 3d visualisation.
- [ ] Windows version
- [ ] MacOS version

### CODE REVIEW

**Comment by mancellin** [comment]
Thanks! 
I managed to build the executable also on Linux (editing the spec file is more portable than my experiments with a shell script...), but the matplotlib display does not seem to work. Is it working for you?

**Comment by RubendeBruin** [comment]
matplotlib works fine here.

**Comment by mancellin** [comment]
Never mind, I tried again in a clean conda environment created with `conda create -c conda-forge capytaine matplotlib pyinstaller` and it worked.

**Comment by RubendeBruin** [comment]
Which imports (besides VTK) would we need to run the 3d visualizations?
Are there any example scripts/recipes that I can test on?

**Comment by mancellin** [comment]
> Which imports (besides VTK) would we need to run the 3d visualizations? Are there any example scripts/recipes that I can test on?

Only VTK I believe.
In the example directory/cookbook, the `animate_free_surface.py` script and `boat_animation.py` script are using a lot of VTK. There is also a `body.show()` in `symmetric_body.py`.

**Comment by RubendeBruin** [comment]
@mancellin ,

capytaine 2.0 seems to be installing just fine with with pip on windows11. No need for any compilers:
image

would this PR still be relevant?

**Comment by mancellin** [comment]
@RubendeBruin Thank you for the feedback!
Yes, I'm still considering publishing a standalone version since many users might not want to deal with package management and virtual environments.

**Comment by RubendeBruin** [comment]
Ok, in that case it may be easiest to use the embed() function of ipython to create a stand-alone ipython version with capytaine and vtk and all included.

Also, using a venv instead of a conda environment drastically reduces the size of the final executable. This has to do with numpy which is installed with a different math kernel if installed from pip.

**Comment by mancellin** [comment]
Following up in its own repository: https://github.com/capytaine/capytaine-standalone

Still some issues with matplotlib at the moment (but VTK works :man_shrugging:).

**Comment by mancellin** [comment]
The standalone distribution at https://github.com/capytaine/capytaine-standalone is (mostly) working.

**Comment by ttammine** [comment]
Hello,

I took my first steps with Capytaine and tested the standalone distribution package.  It seems to be working with Windows  11 nicely but I think there is some problem with capytaine.io.legacy call. I got the following error:

In [39]: from capytaine.io.legacy import export_hydrostatics
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[39], line 1
----> 1 from capytaine.io.legacy import export_hydrostatics

ModuleNotFoundError: No module named 'capytaine.io.legacy'

**Comment by mancellin** [comment]
Thank you @ttammine!
I can reproduce the issue. Not sure why some modules are absent from the standalone distribution. I'll look into it. I opened #448 to keep track of this.

**Pull request closed without merging**
