### PR TITLE
Add minimal_computable_wavelength property to bodies.

### PR DESCRIPTION
**Pull request by mancellin**
It is meant to be used as a lower bound for wavelength ranges, in order to avoid the "insufficient mesh resolution" warnings.

### CODE REVIEW

**Comment by jtgrasb** [comment]
What is the theory behind this minimal wavelength? Can you direct me to a source where I can read up on it? 
--Thanks

**Comment by mancellin** [comment]
The main theoretical justification is [Nyquist–Shannon sampling theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem), that say that you need at least 2 data points per wavelength to discretize a signal.
The value of 4 panels per wavelength is a rule of thumb coming from Nemoh's documentation.

In practice, the results can be surprisingly good for lower wavelengths, but I'm not aware of any deeper study of this topic.

**Comment by mancellin** [comment]
I have in my notes a link to this paper, that I haven't had time to read yet: https://www.worldscientific.com/doi/abs/10.1142/S0218396X02001401

**Comment by jtgrasb** [comment]
Thank you!

**Pull request merged**
